CREATE TABLE FITDATEN(
    ID INT NOT NULL AUTO_INCREMENT,
    BENUTZER ID NOT NULL, 
    ALT INT NOT NULL,
    GEWICHT DECIMAL(5,2) NOT NULL,
    BRUSTUMFANG DECIMAL(7,2) NOT NULL,
    TAILLENUMFAG DECIMAL(7,2) NOT NULL,
    DATEIEN VARCHAR(150),
    PRIMARY KEY(ID)
);
